package validateuserentries1;


import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manideep
 */
public class ValidateUserEntries extends javax.swing.JFrame {

    /**
     * Creates new form ValidateUserEntries
     */
    public ValidateUserEntries() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Sales = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jButton_OK = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validating User Entries");

        jLabel2.setText("Name:");

        jLabel1.setText("Age:");

        jLabel3.setText("Sales:");

        jButton_OK.setText("OK");
        jButton_OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_OKMouseClicked(evt);
            }
        });
        jButton_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKActionPerformed(evt);
            }
        });

        jButton_Exit.setText("Exit");
        jButton_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ExitMouseClicked(evt);
            }
        });
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_OK)
                    .addComponent(jButton_Exit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_OKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_OKMouseClicked
        // TODO add your handling code here:
         
        SwingValidator();
        
        
    }//GEN-LAST:event_jButton_OKMouseClicked

    public void SwingValidator(){
        
        try{
            if(new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false||new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false||new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               if( new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false&&!new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false&&!new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               JOptionPane.showMessageDialog(null, "Please Enter the Name");}
               if( !new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false&&new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false&&!new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               JOptionPane.showMessageDialog(null, "Please Enter the Age");}
               if( !new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false&&!new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false&&new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               JOptionPane.showMessageDialog(null, "Please Enter the Sales");}
               if( !new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false&&new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false&&new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               JOptionPane.showMessageDialog(null, "Please fill the fields Age,Sales");}
               if( new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false&&new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false&&!new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               JOptionPane.showMessageDialog(null, "Please fill the fields Age,Name");}
               if( !new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false&&!new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false&&!new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               JOptionPane.showMessageDialog(null, "Please fill the fields Sales,Name");}
               if( new SwingValidator().isNotEmpty(jTextField_Name, jTextField_Name.getText())==false&&new SwingValidator().isNotEmpty(jTextField_Age, jTextField_Age.getText())==false&&new SwingValidator().isNotEmpty(jTextField_Sales, jTextField_Sales.getText())==false){
               JOptionPane.showMessageDialog(null, "Please fill all the fields");}
            }
            else{
                String a= (jTextField_Name.getText());
                if(new SwingValidator().isInteger(jTextField_Age, jTextField_Age.getText())==true&&new SwingValidator().isDouble(jTextField_Sales, jTextField_Sales.getText())==true){
                 int b= Integer.parseInt(jTextField_Age.getText());
                
                double t=Double.parseDouble(jTextField_Sales.getText());
                JOptionPane.showMessageDialog(null, "Saved!\nEntered Details\nName: "+a+"\n    Age: "+b+"\nSales: "+t);
                jTextField_Age.setText("");
                jTextField_Name.setText("");
                jTextField_Sales.setText("");
                }
                
                
            }}
        catch  (NumberFormatException e){
            JOptionPane.showConfirmDialog(null, "Please enter Details in correct format", "No You Cant Do That! ", JOptionPane.CANCEL_OPTION);
            jTextField_Age.setText("");
            jTextField_Sales.setText("");

        }
    }
    private void jButton_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_OKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_OKActionPerformed

    private void jButton_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitMouseClicked

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidateUserEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidateUserEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidateUserEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidateUserEntries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidateUserEntries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField jTextField_Age;
    public javax.swing.JTextField jTextField_Name;
    public javax.swing.JTextField jTextField_Sales;
    // End of variables declaration//GEN-END:variables
}
